---
title: "Bird Abundance"
author: Alex Gonzales, Ethan Castelazo, Zelda Reif
source: editor
format: 
  pdf:
    include-in-header: 
       text: |
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
         \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}
---

# Set up
## Packages

```{r}
#| label: packages

# general use
library(tidyverse)
library(here)
library(janitor)
library(snakecase)
libray(dpylr)

#Wrap Axis Label
library(scales)

#reading .xlsx files
library(readxl)

# visualize missing data
library(naniar)

# visualizing
library(patchwork)
```

## Data 
```{r}
#| label: data
birds <- read_csv(here("data", "birds.csv"))

venoco_water <- read_csv(here("data", "venoco-water.csv"))

```

## wrangling birds

```{r}
#| label: bird-wrangling


#created a new object from birds
bird_wy2025 <- birds %>% 
  # exclude repeat observations
  mutate(observation_date = as.Date(observation_date, format = "%m/%d/%y")) %>% 
  filter(observation_date > as.Date("2024-11-13") & observation_date < as.Date("2025-10-22"),
         repeat_observation == "No",
         e_bird_group %in% c("Waterfowl",
                             "New World Sparrows",
                             "Martins and Swallows",
                             "Shorebirds")) %>% 
  # filling in taxanomic information about order and families for eBird groups
  mutate(lowest_group = case_when(
    e_bird_group == "New World Sparrows" ~ "Passerellidae",
    e_bird_group == "Martins and Swallows" ~ "Hirundinidae",
    e_bird_group == "Shorebirds" ~ "Charadriiformes",
    e_bird_group == "Waterfowl" ~ "Anatidae"
  ))



# creating new object from most_abundant_groups
abundant_species_counts <- most_abundant_groups %>% 
  # grouping by speices
  group_by(season, e_bird_group, species) %>% 
  # calculating total counts for each species
  summarize(total_count = sum(count)) %>% 
  # arranging in descending order
  arrange(-total_count)
```

## shorebird wrangling

```{r}
#| label: shorebird-wrangling

shorebird_total_count <- bird_wy2025 |> 
  #filter to only include herons, ibis and allies
  filter(lowest_group == "Charadriiformes") |> 
  #group by species
  group_by(species) |> 
  #calc total counts per species
  summarize(total_count = sum(count)) |> 
  #arrange in descending order by total counts
  arrange(-total_count)
```


## wrangling water

```{r}
#| label: water-wrangling

# Creating a new object from venoco_water
venoco_clean <- venoco_water |> 
  # filter to only include 2025 water year
  filter(wy == "2025") |> 
  # creating a new column to convert water elevation in ft to meters
  mutate(comp_level_m = (comp_level_ft + 2.96) * 0.3048) |> 
  # selecting columns of interest
  select(date, comp_level_m, temperature)


# create a new object from Venoco_clean
venoco_daily <- venoco_clean |> 
# group by date
  group_by(date) |> 
# calculate mean water level for each day
  summarize(mean_level_m = mean(comp_level_m, na.rm = TRUE)) |> 
# ungroup the data frame
  ungroup()

```


## joining data frames

```{r}
#| label: joining



```


## plotting birds

```{r}
#| label: shorebird-species-count-plot

ggplot(data = shorebird_total_count,
       # x axis is species in descending order of total count
       # # y axis is total count
       # filling columns by species
       mapping = aes(x = reorder(species, -total_count),
                     y = total_count,
                     fill = species)) + 
  #first layer: column to represent counts
  geom_col() +
  # taking out the legend
  theme(legend.position = "none") +
  #relabelling x and y axes, adding title
  labs(x = "Species",
       y = "Total Count",
       title = "Shorebirds in 2025 Water Year")
```

